### ISSUE TITLE
Do these need column names?

### ISSUE THREAD

**Issue by chrisortman** [OHDSI/CureIdRegistry#34]
https://github.com/OHDSI/CureIdRegistry/blob/539d0da6ae8bcf5f5767c06d374cdaad48b44c5e/Cohort%20curation%20scripts/SEPSIS/01A_SEPSIS_Cohort_V3.sql#L34

**Comment by chrisortman** [comment]
This create table statement I linked to is not valid SQL because it does not specify a name for the last two columns in the statement

**Comment by chrisortman** [comment]
It looks like on https://github.com/OHDSI/CureIdRegistry/blob/539d0da6ae8bcf5f5767c06d374cdaad48b44c5e/Cohort%20curation%20scripts/SEPSIS/01A_SEPSIS_Cohort_V3.sql#L95 the columns are supposed to be `birth_datetime` and `death_datetime`

Those names need to be added to the create table statement

**Comment by DBJHU** [comment]
Updated!  Thank you.
